name : run docker container in work flow 
#here all our steps of the job will run in container instead of VM directly 
on : [push]
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
    steps:
      - name : log node version
        run : |
          node -v 
          cat /etc/os-release