name : actions workflow
on :
  #schedule: 
  #  - cron: "0/3 * * * *"
  push:
    branches:
      - Master
  pull_request:
    branches:
      - Master
    #types: [assigned,opened,reopened]
jobs:
  run-github-actions:
    runs-on : ubuntu-latest
    steps:
      - name: list files before checkout
        run: | 
            pwd
            ls
      - name : checkout repo 
        uses: actions/checkout@v2

      - name: list files after checkout
        run: | 
            pwd
            ls

      - name: simple javascript actions
        id : greet
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet : mazona 
      
      - name : log greeting time 
        run : echo "${{steps.greet.outputs.time}}"