name : matrix workflow
on : [push]
jobs:
  node-version:
    runs-on : ubuntu-latest
    steps :
      - name: node version original 
        run : node -v 
      - name : changing node version 
        uses : actions/setup-node@v2
        with : 
          node-version: '12' 
      - name: node version after modification
        run : node -v 